import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google' 
import SignIn from './MainPages/SignIn'
import Movies from './MainPages/Movies'
 
const inter = Inter({ subsets: ['latin'] })


import logo from "../assets/netflix-logo.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
 
        <SignIn/>
        {/* <Movies/> */}

        {/* <HomeComponents/> */}

  

        {/* <section className=' w-full h-[20rem] bg-slate-400 flex items-center justify-center'>
          <div className='rounded overflow-hidden flex items-center bg-black/80 '>
            <i class="fa-solid fa-magnifying-glass text-lg navIcon px-2" ></i>
            <input className="text-white h-full w-full text-[15px]  bg-black/80" type="text" placeholder=" title, people, genres " />
          </div>         
        </section>  */}

    


      </main>
    </>
  )
}
